export const data = [
  {
    id: 1,
    image: '/mini-cooper.png',
    title: 'Mini Cooper 2020',
    nextReservation: '10/03',
    status: 'Available',
    rating: 4,
  },
  {
    id: 2,
    image: '/mini-cooper.png',
    title: 'Mini Cooper 2020',
    nextReservation: '15/03',
    status: 'Available',
    rating: 5,
  },
  {
    id: 3,
    image: '/mini-cooper.png',
    title: 'Mini Cooper 2020',
    nextReservation: '21/03',
    status: 'Available',
    rating: 3,
  },
  {
    id: 4,
    image: '/mini-cooper.png',
    title: 'Mini Cooper 2020',
    nextReservation: '25/03',
    status: 'Available',
    rating: 2,
  },
  {
    id: 5,
    image: '/mini-cooper.png',
    title: 'Mini Cooper 2020',
    nextReservation: '25/03',
    status: 'Available',
    rating: 1,
  },
  {
    id: 6,
    image: '/mini-cooper.png',
    title: 'Mini Cooper 2020',
    nextReservation: '31/03',
    status: 'Available',
    rating: 3,
  },
];
